### ISSUE TITLE
incompatible version change 0.11

### ISSUE THREAD

**Issue by rubydesign** [retgoat/syncthing-ruby#1]
Hi,
just reading up on synching and noticed that an incompatible change was introduced, also to the rest api as i understand.
So README should mention before/after.
Ideally syncthing-ruby would be upgraded too (though i'm not really using it)
so, just info
T.

**Comment by retgoat** [comment]
Thanks, will check and update

**Comment by retgoat** [comment]
Updated to latest API version https://github.com/retgoat/syncthing-ruby/releases/tag/0.0.3
